### ISSUE TITLE
Removal of Phoenix

### ISSUE THREAD

**Issue by MoskalykA** [BuckshotPlusPlus/BuckshotPlusPlus#1]
Phoenix support should be removed: [https://github.com/BuckshotPlusPlus/BuckshotPlusPlus/tree/main/BuckshotPlusPlus/Compiler/Phoenix](https://github.com/BuckshotPlusPlus/BuckshotPlusPlus/tree/main/BuckshotPlusPlus/Compiler/Phoenix)

**Comment by XoMute** [comment]
Hi @MoskalykA 
I'd like to work on this issue

**Comment by MoskalykA** [comment]
Thanks <3
