### ISSUE TITLE
Fix content on the documentation

### ISSUE THREAD

**Issue by Limerio** [BuckshotPlusPlus/BuckshotPlusPlus#35]
# Fix content on the documentation
## Getting Started/What is buckshot page :
- Change "react js" to "React"
- Add link for PHP and React
- Change to uppercase for "css"
![image](https://github.com/BuckshotPlusPlus/BuckshotPlusPlus/assets/44976231/c612b1fd-5f4a-4686-808f-a475f5bcf589)
- Change to uppersace for "html", "css" and "js"
![image](https://github.com/BuckshotPlusPlus/BuckshotPlusPlus/assets/44976231/d7b5c421-2151-48ce-b5ad-f10a5215e6fc)

## Getting Started/Install page :
- Give an example of a run command to start a buckshot server
![image](https://github.com/BuckshotPlusPlus/BuckshotPlusPlus/assets/44976231/a0cba1ec-f640-4f69-aa93-3d6b32987f43)

## Data-Types/Variables page :
- gitbook doesn't detect the bpp code syntax write the code without it
![image](https://github.com/BuckshotPlusPlus/BuckshotPlusPlus/assets/44976231/a8fa24f4-a889-458e-a6e3-7eeb55a5158b)

## Data-Types/Page page :
- gitbook doesn't detect the bpp code syntax write the code without it
- **page** and not **pager**
![image](https://github.com/BuckshotPlusPlus/BuckshotPlusPlus/assets/44976231/ab4cc487-7d05-414c-8585-a6f12d021ebe)

## The Basics/Conditions page :
- gitbook doesn't detect the bpp code syntax write the code without it
![image](https://github.com/BuckshotPlusPlus/BuckshotPlusPlus/assets/44976231/3497fadf-104b-4655-8b77-d8037156d1e5)

## The Basics/Session page :
- "on" not "in" ![image](https://github.com/BuckshotPlusPlus/BuckshotPlusPlus/assets/44976231/2aca8a39-6ebc-41ba-8cf1-c7f0135d4ec8)
- Remove the "y" of "thye" 
![image](https://github.com/BuckshotPlusPlus/BuckshotPlusPlus/assets/44976231/60300305-0e77-4cf4-ab53-d0174f36ba7b)

**Comment by Vic92548** [comment]
Changes pushed to the doc, thank's!
