### ISSUE TITLE
File CONTRIBUTING.md

### ISSUE THREAD

**Issue by MoskalykA** [BuckshotPlusPlus/BuckshotPlusPlus#4]
You should create the file CONTRIBUTING.md and put the contribution part of the README.md in it

**Comment by muditchoudhary** [comment]
Hey, @MoskalykA  Would like to work on this. Could you assign it to me?

**Comment by MoskalykA** [comment]
> Hey, @MoskalykA Would like to work on this. Could you assign it to me?

Good work !
